/*
 * This file is generated by jOOQ.
 */
package me.jiahuan.java.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import me.jiahuan.java.enums.Gender;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -949253050;

    private Long   uid;
    private String name;
    private Gender gender;

    public User() {}

    public User(User value) {
        this.uid = value.uid;
        this.name = value.name;
        this.gender = value.gender;
    }

    public User(
        Long   uid,
        String name,
        Gender gender
    ) {
        this.uid = uid;
        this.name = name;
        this.gender = gender;
    }

    public Long getUid() {
        return this.uid;
    }

    public User setUid(Long uid) {
        this.uid = uid;
        return this;
    }

    @NotNull
    @Size(max = 10)
    public String getName() {
        return this.name;
    }

    public User setName(String name) {
        this.name = name;
        return this;
    }

    @NotNull
    public Gender getGender() {
        return this.gender;
    }

    public User setGender(Gender gender) {
        this.gender = gender;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (uid == null) {
            if (other.uid != null)
                return false;
        }
        else if (!uid.equals(other.uid))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!gender.equals(other.gender))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uid == null) ? 0 : this.uid.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(uid);
        sb.append(", ").append(name);
        sb.append(", ").append(gender);

        sb.append(")");
        return sb.toString();
    }
}
