/*
 * This file is generated by jOOQ.
 */
package me.jiahuan.java.model;


import javax.annotation.Generated;

import me.jiahuan.java.model.tables.User;


/**
 * Convenience access to all tables in j2ee-learn
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>j2ee-learn.user</code>.
     */
    public static final User USER = me.jiahuan.java.model.tables.User.USER;
}
