/*
 * This file is generated by jOOQ.
 */
package me.jiahuan.java.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.jiahuan.java.model.tables.User;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class J2eeLearn extends SchemaImpl {

    private static final long serialVersionUID = -1999088639;

    /**
     * The reference instance of <code>j2ee-learn</code>
     */
    public static final J2eeLearn J2EE_LEARN = new J2eeLearn();

    /**
     * The table <code>j2ee-learn.user</code>.
     */
    public final User USER = me.jiahuan.java.model.tables.User.USER;

    /**
     * No further instances allowed
     */
    private J2eeLearn() {
        super("j2ee-learn", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
